### ISSUE TITLE
2.1.1 Failed to resolve entry for package "@portabletext/svelte".

### ISSUE THREAD

**Issue by nermolov** [portabletext/svelte-portabletext#51]
Since upgrading to Svelte 4 and updating `@portabletext/svelte` from `2.0.0` to `2.1.1`, my project has stopped building with the following error:

(this same error also occurs in dev mode)
```
npm run build

> svelte-latest-check@0.0.1 build
> vite build


vite v4.4.9 building SSR bundle for production...
✓ 33 modules transformed.
✓ built in 267ms
[commonjs--resolver] Failed to resolve entry for package "@portabletext/svelte". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@portabletext/svelte". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:28688:5)
    at tryNodeResolve (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Object.resolveId (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.handler (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:48234:19)
    at file:///home/nik/playground/cdc/svelte-latest-check/node_modules/rollup/dist/es/shared/node-entry.js:25461:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/rollup/dist/es/shared/node-entry.js:25361:28)
    at async resolveId (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/rollup/dist/es/shared/node-entry.js:24035:26)
    at async ModuleLoader.resolveId (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/rollup/dist/es/shared/node-entry.js:24449:15)
    at async Object.resolveId (file:///home/nik/playground/cdc/svelte-latest-check/node_modules/vite/dist/node/chunks/dep-df561101.js:7910:10)
```

Updating `@svelte/portabletext`'s `package.json` `exports` field to specify a default export fixes the issue, so I assume that's what's needed?

```
  "exports": {
    "./package.json": "./dist/package.json",
    ".": "./dist/index.js"
  },
```

Here's a full issue reproduction repository, created with `npm create svelte@latest`, then installing latest @svelte/portabletext packages `npm install @portabletext/svelte@latest @portabletext/types@latest`

https://github.com/nermolov/portabletext-svelte-issue-reproduction

**Comment by cristianvogel** [comment]
I am totally having the same issue! It hadn't occurred to me that it might have been the Svelte version...

**Comment by cristianvogel** [comment]
So I've had this all day and I am not sure it is Svelte version. 

I have two workspaces - one is the Sanity.io template for Sveltekit. This one resolves "@portabletext/svelte" just fine. 
<img width="561" alt="Screenshot 2023-08-26 at 19 47 52" src="https://github.com/portabletext/svelte-portabletext/assets/12829050/57bb5cd8-bf54-49c6-991e-7a601c10b687">

But my real world project simply doesn't want to resolve the entry. As you can see, it clearly exists. 
<img width="720" alt="Screenshot 2023-08-26 at 19 51 09" src="https://github.com/portabletext/svelte-portabletext/assets/12829050/a217ade9-b5d3-429a-9c8d-e9afd3a61894">

**Comment by cristianvogel** [comment]
@nermolov 's fix didn't resolve it for me.... did I do it correctly?  

```json
  "type": "module",
  "exports": {
    "./package.json": "./dist/package.json",
    ".": "./dist/index.js"
  },

**Comment by nermolov** [comment]
Running node v18.17.1 and npm 9.6.7.

Some new/extra info -- It seems the issue is two-fold, typescript not supporting the `exports` -> `.` -> `types` directive for exposing types, and svelte preferring the `default` export over the `svelte` export, which causes it to keel over when the `default` export points to a non-existing file (as it does currently in this repository).

I've forked the package with no changes other than updating exports/types in `package.json`, and consuming this package works well for me, thinking that is all that would be needed to fix this issue.

[`package.json`](https://github.com/nermolov/svelte-portabletext/blob/e1c51f311d9b4f45193d9385a23e86d183907e25/package.json#L12-L18)
```
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "svelte": "./dist/index.js"
    }
  },
  "types": "./dist/index.d.ts",
```

**Comment by RedrumIzBak** [comment]
The file ./dist/bar.js is missing and removing that from the package.json exports resolved our issue.

**Comment by nermolov** [comment]
Yup, removing the missing default export resolves the build error, I just also needed to add `types` to the top level of the package.json to get TS to pick up types properly.

**Comment by LiamGallagher737** [comment]
I tried using your fork @nermolov but am still getting the issue.
![image](https://github.com/portabletext/svelte-portabletext/assets/86995276/76aa240f-b256-400a-9b55-3342c85a0e7d)
This is the deps in my `package.json`
![image](https://github.com/portabletext/svelte-portabletext/assets/86995276/c7349099-d90f-48e1-a654-2e06d2d03994)
(It's possible I've just done something wrong, never used git imports with node before)

**Comment by nermolov** [comment]
@LiamGallagher737 I published the forked package to github's package registry and have been using it that way https://github.com/nermolov/svelte-portabletext/pkgs/npm/svelte-portabletext

**Comment by liegeandlief** [comment]
Can confirm the fix by @nermolov works. I have applied it using `patch-package` for now, but would be good if this could be fixed!

**Comment by eystein** [comment]
Just gotta share my "fix" for this as well, as I've spent 10 hours(!) on this problem. 

I used [patch-package](https://github.com/ds300/patch-package) (thanks @liegeandlief !) , but since I have a monorepo with hoisting I had to disable hoisting for the `@portabletext/svelte` package. 
```
// In child repo
 "workspaces": {
    "nohoist": [
      "@portabletext",
      "@portabletext/**"
    ]
  },
```

And in the `package.json` for `@portabletext/svelte` I changed:
```
"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js", // <-- Was bar.js, changed it to index.js
      "svelte": "./dist/index.js"
    }
  },
```

This now works on both local dev and on Vercel. Hopefully this save someone some time. 

Sidenote: I couldn't get the fix from @nermolov working because I only got the unbuild source instead of the package with the `dist` folder.

**Comment by cristianvogel** [comment]
Nice one @eystein !
Will give your "fix" a go.

**Comment by olivergburke** [comment]
Thanks @eystein, that worked for me!

For anyone else having this issue, steps were:
- Follow the set-up and install steps on the patch-package repo
- Edit the package.json for the @portabletext/svelte in node_modules from `"default": "./dist/bar.js",` to `"default": "./dist/index.js",`
- Run `npx patch-package @portabletext/svelte --exclude`. I had to add the exclude tag for patch-package to recognize changes in the package.json file

Note that I don't have a monorepo, so I didn't need to disable hoisting like above.

Hopefully this gets fixed soon

**Comment by kjaonline** [comment]
Is there an ETA for the fix for this?

**Comment by alexanderbnelson** [comment]
For anyone that cares, I just swapped out NPM for Yarn and had no issues with build when deploying to Vercel. I couldn't get @eystein or @nermolov's solutions to work os tried Yarn as a last ditch attempt. Had tried Bun too. No luck. Obviously a simple package update would be preferable.

**Comment by nmowatt** [comment]
> For anyone that cares, I just swapped out NPM for Yarn and had no issues with build when deploying to Vercel. I couldn't get @eystein or @nermolov's solutions to work so tried Yarn as a last ditch attempt. Had tried Bun too. No luck. Obviously a simple package update would be preferable.

How exactly? I tried using yarn now instead and it fails with the exact same error:

```
Failed to resolve entry for package "@portabletext/svelte". The package may have incorrect main/module/exports specified in its package.json
```

**Comment by ScriptPunkio** [comment]
I was able to get it to work by removing the `^` from the version and setting my dependency to `"@portabletext/svelte": "2.0.0",`.

**Comment by ileys-admin** [comment]
> Running node v18.17.1, npm 9.6.7, typescript 5.1.6.
> 
> Some new/extra info -- It seems the issue is two-fold, typescript not supporting the `exports` -> `.` -> `types` directive for exposing types, and svelte preferring the `default` export over the `svelte` export, which causes it to keel over when the `default` export points to a non-existing file (as it does currently in this repository).
> 
> I've forked the package with no changes other than updating exports/types in `package.json`, and consuming this package works well for me, thinking that is all that would be needed to fix this issue.
> 
> [`package.json`](https://github.com/nermolov/svelte-portabletext/blob/e1c51f311d9b4f45193d9385a23e86d183907e25/package.json#L12-L18)
> 
> ```
>   "exports": {
>     ".": {
>       "types": "./dist/index.d.ts",
>       "svelte": "./dist/index.js"
>     }
>   },
>   "types": "./dist/index.d.ts",
> ```

Thank you so much it was eating me  for 2 hours

**Comment by kmelve** [comment]
Apologies for missing this folks! I've brought to the attention of the team and hopefully we'll be able to remedy it soon.

**Comment by nickisnoble** [comment]
This is obviously not ideal, but at least gets things to build:

`vite.config.ts`

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	resolve: {
		alias: {
			'@portabletext/svelte': '/node_modules/@portabletext/svelte/dist/index.js',
		},
	}
});
```

**Comment by kmelve** [comment]
This should be fixed in #57. Thanks so much for the PR, @patrickedqvist! 

Let us know if something else comes up.

**Comment by liegeandlief** [comment]
@kmelve I think it's only partially fixed. As mentioned in https://github.com/portabletext/svelte-portabletext/issues/51#issuecomment-1694485309 `"types": "./dist/index.d.ts",` needs adding to the top level of `package.json` for TypeScript to pick up the types correctly.

**Comment by kmelve** [comment]
Thanks for calling that out @liegeandlief! Pushed a fix for that as well. https://github.com/portabletext/svelte-portabletext/releases/tag/v2.1.3
